- name: ensure predictable network intarface names are disabled
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
  notify: update grub

- name: ensure internal and external interfaces are properly configured
  template: >-
    src=etc/network/interfaces
    dest=/etc/network/interfaces
    owner=root
    group=root
    mode=0644
